export const GET_CREDENTIALS_START = 'GET_CREDENTIALS_START'; 
export const GET_CREDENTIALS_SUCCESS = 'GET_CREDENTIALS_SUCCESS';
export const GET_CREDENTIALS_FAIL = 'GET_CREDENTIALS_FAIL'; 

export const RECOVER_PASSWORD_START = 'RECOVER_PASSWORD_START'; 
export const RECOVER_PASSWORD_SUCCESS = 'RECOVER_PASSWORD_SUCCESS';
export const RECOVER_PASSWORD_FAIL = 'RECOVER_PASSWORD_FAIL'; 

export const LOGOUT = 'LOGOUT';

export const GET_SITEGROUPS_START = 'GET_SITEGROUPS_START';
export const GET_SITEGROUPS_SUCCESS = 'GET_SITEGROUPS_SUCCESS'; 
export const GET_SITEGROUPS_FAIL = 'GET_SITEGROUPS_FAIL'; 

export const GET_SITES_START = 'GET_SITES_START';
export const GET_SITES_SUCCESS = 'GET_SITES_SUCCESS';
export const GET_SITES_FAIL = 'GET_SITES_FAIL';

export const GET_DEVICES_START = 'GET_DEVICES_START';
export const GET_DEVICES_SUCCESS = 'GET_DEVICES_SUCCESS';
export const GET_DEVICES_FAIL = 'GET_DEVICES_FAIL';

export const GET_DEVICE_VALUES_START = 'GET_DEVICE_VALUES_START';
export const GET_DEVICE_VALUES_SUCCESS = 'GET_DEVICE_VALUES_SUCCESS';
export const GET_DEVICE_VALUES_FAIL = 'GET_DEVICE_VALUES_FAIL';

export const GET_SENSOR_VALUES_START = 'GET_SENSOR_VALUES_START'; 
export const GET_SENSOR_VALUES_SUCCESS = 'GET_SENSOR_VALUES_SUCCESS';
export const GET_SENSOR_VALUES_FAIL = 'GET_SENSOR_VALUES_FAIL';

export const GET_LATEST_SENSOR_VALUES_START = 'GET_LATEST_SENSOR_VALUES_START';
export const GET_LATEST_SENSOR_VALUES_SUCCESS = 'GET_LATEST_SENSOR_VALUES_SUCCESS';
export const GET_LATEST_SENSOR_VALUES_FAIL = 'GET_LATEST_SENSOR_VALUES_FAIL';

export const GET_PERIOD_SENSOR_VALUES_START = 'GET_PERIOD_SENSOR_VALUES_START';
export const GET_PERIOD_SENSOR_VALUES_SUCCESS = 'GET_PERIOD_SENSOR_VALUES_SUCCESS';
export const GET_PERIOD_SENSOR_VALUES_FAIL = 'GET_PERIOD_SENSOR_VALUES_FAIL';

export const GET_SENSOR_LIST_START = 'GET_SENSOR_LIST_START';
export const GET_SENSOR_LIST_SUCCESS = 'GET_SENSOR_LIST_SUCCESS';
export const GET_SENSOR_LIST_FAIL = 'GET_SENSOR_LIST_FAIL';

export const GET_SENSOR_MEDIAN_VALUES_START = 'GET_SENSOR_MEDIAN_VALUES_START';
export const GET_SENSOR_MEDIAN_VALUES_SUCCESS = 'GET_SENSOR_MEDIAN_VALUES_SUCCESS';
export const GET_SENSOR_MEDIAN_VALUES_FAIL = 'GET_SENSOR_MEDIAN_VALUES_FAIL';

export const GET_SENSOR_TRENDS_START = 'GET_SENSOR_TRENDS_START';
export const GET_SENSOR_TRENDS_SUCCESS = 'GET_SENSOR_TRENDS_SUCCESS';
export const GET_SENSOR_TRENDS_FAIL = 'GET_SENSOR_TRENDS_FAIL';